-- Create schema (if not exists)
CREATE SCHEMA IF NOT EXISTS inventory_db;

-- Table creation
CREATE TABLE inventory_db.inventory_copper_service (
    path_name VARCHAR(100),
    category VARCHAR(30),
    voice_equipment_type VARCHAR(30),
    voice_exchange_id VARCHAR(100),
    voice_equipment_clli VARCHAR(50),
    voice_slot VARCHAR(30),
    voice_port VARCHAR(50),
    voice_access_port_id VARCHAR(100),
    voice_en VARCHAR(3100),
    voice_node_name VARCHAR(3100),
    voice_node_up_slot VARCHAR(30),
    voice_node_up_port VARCHAR(50),
    voice_node_ip_address VARCHAR(3100),
    voice_v5_id VARCHAR(3100),
    voice_switch_id VARCHAR(3100),
    voice_host_exchange_switch VARCHAR(3100),
    voice_switch_type VARCHAR(3100),
    voice_switch_name VARCHAR(3100),
    voice_nms_jv_code VARCHAR(3100),
    voice_switch_model VARCHAR(3100),
    voice_agg_name VARCHAR(3100),
    voice_agg_clli VARCHAR(50),
    voice_agg_ip VARCHAR(3100),
    voice_agg_primary_port VARCHAR(4000),
    voice_agg_standby_port VARCHAR(4000),
    data_equipment_type VARCHAR(30),
    data_node_name VARCHAR(3100),
    data_node_up_slot VARCHAR(30),
    data_node_up_port VARCHAR(50),
    data_node_ip_address VARCHAR(3100),
    data_equipment_clli VARCHAR(50),
    data_slot VARCHAR(30),
    data_port VARCHAR(50),
    data_access_port_id VARCHAR(100),
    data_en VARCHAR(3100),
    data_el VARCHAR(3100),
    copper_cabinet VARCHAR(4000),
    cabinet_strip_pair_dp_pair CHAR(1),
    primary_strip_cable VARCHAR(80),
    secondary_strip_cable VARCHAR(80),
    data_v5_id VARCHAR(3100),
    data_exchange_id VARCHAR(3100),
    data_host_exchange_switch VARCHAR(3100),
    data_switch_id VARCHAR(3100),
    data_switch_type VARCHAR(3100),
    data_switch_name VARCHAR(3100),
    data_nms_jv_code VARCHAR(3100),
    data_agg_name VARCHAR(3100),
    data_agg_clli VARCHAR(50),
    data_agg_ip VARCHAR(3100),
    data_agg_primary_port VARCHAR(3100),
    data_agg_standby_port VARCHAR(3100),
    copper_plate_id VARCHAR(3100),
    plate_latitude VARCHAR(20),
    plate_id_longitude VARCHAR(20),
    domain_name TEXT,
    plate_district VARCHAR(3100),
    plate_region VARCHAR(3100),
    plate_exchange VARCHAR(3100),
    treatment_priority CHAR(1),
    mdf_name VARCHAR(100),
    mdf_slot VARCHAR(30),
    mdf_port VARCHAR(50),
    class_a VARCHAR(3100),
    telephone_number VARCHAR(3100),
    last_mod_ts TIMESTAMP,
    circuit_path_name VARCHAR(100)
);

-- Index creation
CREATE INDEX inventory_copper_service_ix1 
ON inventory_db.inventory_copper_service (
    last_mod_ts DESC
);
